site :opscode

cookbook 'apt'
cookbook 'build-essential'
cookbook 'composer'
cookbook 'iptables'
cookbook 'memcached'
cookbook 'monit'
cookbook 'monit_bin'
cookbook 'mysql'
cookbook 'nginx'
cookbook 'ohai'
cookbook 'openssl'
cookbook 'pdepend'
cookbook 'php-fpm'
cookbook 'php'
cookbook 'phpcpd'
cookbook 'phpdoc'
cookbook 'phpmd'
cookbook 'phpunit'
cookbook 'runit'
cookbook 'xml'
cookbook 'yum'

